all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "admin"

prod:
  hosts:
    client1:
      ansible_host: 10.0.2.4
      instance_1:
        name: ENSUP
        title: Ensup Student
        port: 8080
        site_name: webapp
        docker_name: webapp
